Common_EventScript_SetGymTrainers::
	switch FLAG_GARBAGEFLAG
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	settrainerflag TRAINER_NONE
	return
